# pubspec.yaml
name: config
description: Config for Clients.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  base:
    path: ../base

