name: base
description: Default code for contacten-app.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  config:
    path: config
    
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  http: ^0.13.3
  cached_network_image: ^3.1.0
  font_awesome_flutter: ^9.1.0
  google_maps_flutter: ^2.0.11
  dart_twitter_api: ^0.5.3
  # splash_screen_view: ^3.0.0
  tweet_ui: ^3.0.1
  image_picker: ^0.8.4+2
  location: ^4.2.0
  url_launcher: ^6.0.12
  json_serializable: ^5.0.2
  twitter_intent: 1.0.0-nullsafety.1
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  flutter_datetime_picker: ^1.5.1
  page_transition: "^2.0.4"
  flutter_native_splash: ^1.3.0  

flutter_native_splash:
  color: "#ffffff"
  image: config/assets/images/splash.png
  android: true
  ios: true
 
  #background_image_dark: "assets/dark-background.png"
  #image_dark: config/assets/images/company.png
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4  
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_config: ^2.0.0  

flutter_icons:
  android: true
  ios: true
  image_path: "config/assets/images/launcher_icon.jpg"

# The following section is specific to Flutter.

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: config/assets/fonts/OpenSans-Regular.ttf
    - family:  CustomKeyIcon
      fonts:
        - asset: config/assets/fonts/key.ttf
 
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - config/assets/images/

